name: "Setup dependencies"

inputs:
  NODE_VERSION:
    description: "The version of Node.js to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: "pnpm"
        cache-dependency-path: "./pnpm-lock.yaml"

    - name: Display version of node.js, pnpm
      run: |
        node -v
        pnpm -v
      shell: bash

    - name: Install dependencies
      run: |
        pnpm install
      shell: bash
