name: ci-on-pr

on: 
  push:
    branches: 
      - 'develop'
      - 'master'
  pull_request:
    branches: 
      - 'develop'
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
        with:
          NODE_VERSION: ${{ matrix.node-version }}

  build:
    runs-on: ubuntu-latest
    needs: setup-dependencies
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          NODE_VERSION: ${{ matrix.node-version }}

      - name: build
        run: pnpm build

  lint:
    runs-on: ubuntu-latest
    needs: setup-dependencies
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          NODE_VERSION: ${{ matrix.node-version }}

      - name: lint
        run: pnpm lint
  
  check-version:
    runs-on: ubuntu-latest
    # master への PR の時のみ実施
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'

    steps:
      # master と PRの HEAD をチェックアウトする
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # master ブランチのバージョンを取得
      - name: Get master version
        id: get_master_version
        run: |
          echo "version=$(git show origin/master:package.json | jq -r '.version')" >> $GITHUB_OUTPUT


      # PR ブランチのバージョンを取得
      - name: Get PR version
        id: get_pr_version
        run: |
          echo "version=$(git show HEAD:package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      # PR ブランチのバージョンが master ブランチのバージョンと一致する場合は fail
      - name: Check version
        run: |
          if [ "${{ steps.get_master_version.outputs.version }}" = "${{ steps.get_pr_version.outputs.version }}" ]; then
            echo "Version is same"
            exit 1
          else
            echo "Version is different"
          fi
